version: '2'
services:

  flightplanclient:
    image: p2bauer/flightplandocker:client
    container_name: flightplanclient
    ports:
      - '3000:3000'
  flightplanserver:
    image: p2bauer/flightplandocker:server
    container_name: flightplanserver
    ports:
      - '5000:5000'
    volumes:
     - ~/config:/flightplan/config
     - ~/data:/flightplan/data
